apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "looker.name" . }}'
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "looker.labels" . | nindent 4 }}
data:
  {{- if .Values.global.ingress.enabled }}
  HOST_URL: '{{ ternary "https" "http" .Values.global.ingress.tls.enabled }}://{{ first .Values.ingress.hosts }}'
  {{ else if .Values.global.istio.enabled }}
  HOST_URL: '{{ ternary "https" "http" (not (empty .Values.global.istio.tls)) }}://{{ first .Values.istio.virtualService.hosts }}'
  {{- end}}
  FIRST_NAME: '{{ .Values.config.firstName }}'
  LAST_NAME: '{{ .Values.config.lastName }}'
  EMAIL: '{{ .Values.config.email }}'
  {{- if .Values.global.database.timescaledb.installed }}
  TIMESCALE_HOST: '{{ .Values.config.timescaleHost }}'
  TIMESCALE_PORT: '{{ .Values.config.timescalePort }}'
  TIMESCALE_SSL: 'false'
  {{- else }}
  TIMESCALE_HOST: {{ (split ":" (index .Values.global.database.timescaledb.hosts 0))._0 }}
  TIMESCALE_PORT: {{ (split ":" (index .Values.global.database.timescaledb.hosts 0))._1 | quote }}
  TIMESCALE_SSL: 'true'
  {{- end }}  
  TIMESCALE_CONNECTION_NAME: '{{ .Values.config.timescaleConnectionName }}'
  TIMESCALE_DATABASE: '{{ .Values.config.timescaleDatabase }}'
  TIMESCALE_CONNECTION_NAME_FF: '{{ .Values.config.ffConnectionName }}'
  TIMESCALE_DATABASE_FF: '{{ .Values.config.ffDatabase }}'
  POSTGRES_CONNECTION_NAME: '{{ .Values.config.stoConnectionName }}'
  POSTGRES_HOST: '{{ .Values.config.timescaleHost }}'
  POSTGRES_PORT: '{{ .Values.config.timescalePort }}'
  POSTGRES_DATABASE: '{{ .Values.config.stoDatabase }}'
  CLICKHOUSE_CONNECTION_NAME: {{ .Values.config.clickhouseConnectionName }}
  CLICKHOUSE_HOST: {{ .Values.config.clickhouseHost }}
  CLICKHOUSE_PORT: {{ .Values.config.clickhousePort | quote }}
  CLICKHOUSE_DATABASE: {{ .Values.config.clickhouseDatabase }}
  CLICKHOUSE_USER: {{ .Values.config.clickhouseUser }}
  PROJECT_NAME: '{{ .Values.config.projectName }}'
  DOMAIN_WHITELIST: {{ .Values.global.loadbalancerURL }}
  MODELS_DIR: {{ .Values.modelsDirectory }}
  {{- if .Values.mysql.enabled }}
  LOOKER_MYSQL_HOST: {{ .Values.mysql.host }}
  LOOKER_MYSQL_USERNAME: {{ .Values.mysql.user }}
  LOOKER_MYSQL_DATABASE: {{ .Values.mysql.database }}
  LOOKER_MYSQL_PORT: {{ .Values.mysql.port | quote }}
  {{- end}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: looker-startup-options
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "looker.labels" . | nindent 4 }}
data:
  lookerstart.cfg: |
    LOOKERARGS="--no-ssl --shared-storage-dir={{ .Values.modelsDirectory }}
    {{- if .Values.mysql.enabled }}
    -d looker-db.yml
    {{- end}}
    "
