{{- if .Values.global.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ include "looker.name" . }}'
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.global.ingress.className }}
  ingressClassName: {{ .Values.global.ingress.className | quote }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ include "looker.name" $ }}-web'
                port:
                  name: looker-web
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: 'hrns-{{ include "looker.name" $ }}-api'
                port:
                  name: looker-api
          - path: /api-docs/
            pathType: Prefix
            backend:
              service:
                name: 'hrns-{{ include "looker.name" $ }}-api'
                port:
                  name: looker-api
          - path: /versions
            pathType: Prefix
            backend:
              service:
                name: 'hrns-{{ include "looker.name" $ }}-api'
                port:
                  name: looker-api
          - path: /api/internal/
            pathType: Prefix
            backend:
              service:
                name: '{{ include "looker.name" $ }}-web'
                port:
                  name: looker-web
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}

{{- end }}
