apiVersion: v1
kind: Secret
metadata:
  name: looker-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "looker.generateLookerInternalSecrets" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: harness-looker-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "looker.generateLookerSecrets" . }}
