{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: looker-mysql-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "looker.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "looker.generateMysqlSecrets" . }}
{{- end}}
